name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rustlang/rust:nightly
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all --tests --benches
    - name: Run tests
      run: cargo test --verbose

  security:
    runs-on: ubuntu-latest
    container:
      image: rustlang/rust:nightly
    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Cargo Audit
      run: cargo audit
    
